from openai import OpenAI

from services.config import OPENAI_API_KEY

client = OpenAI(api_key=OPENAI_API_KEY)

conversation_memory = {}

MAX_HISTORY = 20


def generate_reply(
    sender_id: str,
    text: str,
    intent: str,
    sentiment: str,
):
    """
    Generate an AI reply while remembering previous messages
    from the same Messenger user.
    """

    history = conversation_memory.setdefault(sender_id, [])

    # Store newest user message
    history.append(
        {
            "role": "user",
            "content": text,
        }
    )

    # Keep only the newest messages
    history[:] = history[-MAX_HISTORY:]

    # Context generated by your ML pipeline
    conversation_context = {
        "role": "system",
        "content": (
            "Conversation analysis:\n"
            f"- Intent: {intent}\n"
            f"- Sentiment: {sentiment}\n\n"
            "Use this information to adjust your response."
        ),
    }

    # Main assistant instructions
    assistant_prompt = {
        "role": "system",
        "content": (
            "You are a friendly AI customer support assistant.\n"
            "Reply naturally.\n"
            "Keep answers under 80 words.\n"
            "If the user is frustrated, be empathetic.\n"
            "If they are happy, match their enthusiasm.\n"
            "Do not mention the detected intent or sentiment."
        ),
    }

    response = client.responses.create(
        model="gpt-5-mini",
        input=[
            assistant_prompt,
            conversation_context,
            *history,
        ],
        max_output_tokens=500,
    )

    print("========== OPENAI RESPONSE ==========")
    print(response)
    print("=====================================")

    reply = response.output_text

    if not reply or not reply.strip():
        reply = "Sorry, I couldn't generate a response."

    print("OUTPUT TEXT:")
    print(repr(reply))

    history.append(
        {
            "role": "assistant",
            "content": reply,
        }
    )

    history[:] = history[-MAX_HISTORY:]

    print("========== CONVERSATION MEMORY ==========")
    print(f"Messages stored: {len(history)}/{MAX_HISTORY}")

    for message in history:
        print(message)

    print("=========================================")

    return reply